### ISSUE TITLE
Site is down 

### ISSUE THREAD

**Issue by Daniel3356** [randomkrishna/file-tree-js#2]
Hi, 
The demo website is down. 

Thanks for fixing it.

**Comment by randomkrishna** [comment]
Hi, thanks for letting me know. Demo website is up now.

**Comment by Daniel3356** [comment]
I am still getting Site not found
Looks like you followed a broken link or entered a URL that doesn’t exist on Netlify.

**Comment by randomkrishna** [comment]
they changed .com to .app

here's correct link -> https://file-tree.netlify.app/
